baseurl: "https://mvpotter.github.io/mvpotter/"
theme: "hugo-bearblog"
title: "Mikhail Potter"
author: "Mikhail Potter"
languageCode: "en-us"
disqusShortname: "mvpotter"
enableRobotsTXT: true

params:
  hideMadeWithLine: false

menu:
  main:
    - name: Blog
      url: /
      weight: 10
    - name: CV
      url: "/cv.pdf"
      weight: 20
    - name: Linkedin
      url: https://www.linkedin.com/in/supermegapotter
      weight: 30
    - name: GitHub
      url: https://github.com/mvpotter
      weight: 40  
    - name: Medium
      url: https://medium.com/@supermegapotter
      weight: 50 

